version: '3.8'

services:
  streamlit:
    build: .
    image: chatbot:latest
    container_name: chatbot_app
    ports:
      - "8501:8501"
    volumes:
      - chatbot_data:/app/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONUNBUFFERED=1

volumes:
  chatbot_data:

